# Generated by scripts/gen-bash-completion.py — DO NOT EDIT BY HAND.
# Regenerate with: make gen-completion

_agent_complete_verbs="create legacy_stats logs rebuild run stats update"
_agent_complete_passthrough_verbs="run"
_agent_complete_flags_create=""
_agent_complete_flags_legacy_stats="--days"
_agent_complete_flags_logs="--port --stop"
_agent_complete_flags_rebuild="--full"
_agent_complete_flags_run="--base"
_agent_complete_flags_stats="--verbose --days"
_agent_complete_flags_update=""
