# This file has been created with the assistance of an AI tool.
#
# Compiles bash tab-completion data for the `agent` command from the command
# modules under agent_wrap/commands/. Walks the discovered commands (the same
# source of truth as `agent` with no args) and writes a sourceable bash file
# of verbs and per-verb flags that agent-wrap.bashrc relies on entirely.
#
# Usage:
#   python3 scripts/gen-bash-completion.py            # write the data file
#   python3 scripts/gen-bash-completion.py --check     # fail if it is stale
#
# Exit codes:
#   0 - file written (default), or file is up to date (--check)
#   1 - committed file is stale (--check only)

from __future__ import annotations

import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_OUTPUT = _ROOT / "agent-wrap-completion.bash"

# Make the package importable when run as a standalone script.
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from agent_wrap.__main__ import _discover_commands  # noqa: E402

# Flags are declared in each command module's USAGE string, e.g. "[--port N]".
# Same pattern the old drift test used, keeping USAGE the source of truth.
_FLAG_RE = re.compile(r"--[a-z][a-z0-9-]*")

_HEADER = (
    "# Generated by scripts/gen-bash-completion.py — DO NOT EDIT BY HAND.\n"
    "# Regenerate with: make gen-completion\n"
)


def generate() -> str:
    """Render the sourceable bash completion-data file from discovered commands."""
    commands = _discover_commands()

    verbs = sorted(c.name for c in commands)
    # A verb forwards trailing args to another program (file completion) when its
    # USAGE advertises a `...` passthrough, e.g. run's "[--base] [claude-args...]".
    passthrough = sorted(c.name for c in commands if "..." in c.usage)

    lines = [_HEADER]
    lines.append(f'_agent_complete_verbs="{" ".join(verbs)}"')
    lines.append(f'_agent_complete_passthrough_verbs="{" ".join(passthrough)}"')

    for cmd in sorted(commands, key=lambda c: c.name):
        # Preserve first-seen order while de-duplicating repeated flags.
        flags = list(dict.fromkeys(_FLAG_RE.findall(cmd.usage)))
        lines.append(f'_agent_complete_flags_{cmd.name}="{" ".join(flags)}"')

    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    content = generate()

    if check:
        current = _OUTPUT.read_text(encoding="utf-8") if _OUTPUT.exists() else ""
        if current != content:
            print(
                f"ERROR: {_OUTPUT.name} is out of date. Run `make gen-completion`.",
                file=sys.stderr,
            )
            return 1
        print(f"{_OUTPUT.name} is up to date.")
        return 0

    _OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {_OUTPUT.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
